#!/usr/bin/env python3
"""Generate every MASTER_*.md report from master-dataset.json.

Reports are generated, never hand-written, so no number in them can drift from the extraction.
Every percentage is a COUNT over discovered elements — the denominator is stated inline so the
reader can check the arithmetic.
"""
import json, os
from collections import Counter, defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
D = json.load(open(os.path.join(HERE, 'master-dataset.json'), encoding='utf-8'))
HDR = ("> Generated by `gen_reports.py` from `master-dataset.json`. Every figure is a count over\n"
       "> extracted evidence; nothing here is an estimate. Items without evidence appear as UNKNOWN\n"
       "> and are never invented.\n")


def w(name, body):
    with open(os.path.join(HERE, name), 'w', encoding='utf-8') as f:
        f.write(body)
    print(f'  {name}')


def pct(a, b):
    return f'{(100.0 * a / b):.1f}%' if b else 'n/a'


# ------------------------------------------------------------------ API
api, rb = D['originalApi'], D['rebuildApi']
eps = api['endpoints']
by_cat = defaultdict(list)
for e in eps:
    by_cat[e['category'] or 'uncategorised'].append(e)
rb_by_mod = Counter(r['module'] for r in rb['routes'])

rows = []
for cat, items in sorted(by_cat.items(), key=lambda kv: -len(kv[1])):
    live = sum(1 for e in items if e['liveStatus'] == 'OK')
    shaped = sum(1 for e in items if (e.get('responseShape') or '').strip() not in ('{  }', '{}', '', None))
    rows.append(f"| {cat} | {len(items)} | {live} | {shaped} |")

w('MASTER_API_MAP.md', f"""# MASTER API MAP

{HDR}
## 1. The original surface is larger than any single source shows

| Source | Endpoints | How obtained |
|---|---:|---|
| Static APK analysis (`API_SCHEMA.json`) | {api['fromApkStatic']} | decrypted strings + decompiled Gson DTOs |
| Live H5 traffic capture (`h5_api_contract.json`) | {api['fromH5LiveCapture']} | real requests through the signed gateway |
| **Overlap** | **{api['overlap']}** | — |
| **TRUE UNION** | **{api['endpointCount']}** | the real known original surface |

**This matters.** Earlier reports in this project used 280 as the denominator. The two evidence
sources are almost disjoint — they overlap on only {api['overlap']} ids — so the honest figure is
their union, **{api['endpointCount']}**. Every parity percentage below uses that denominator, which
makes prior estimates optimistic by roughly a third.

## 2. Evidence quality

| Property | Count | Share |
|---|---:|---:|
| Endpoints with ANY live evidence | {api['withLiveEvidence']} | {pct(api['withLiveEvidence'], api['endpointCount'])} |
| Endpoints with a captured response shape | {api['withResponseShape']} | {pct(api['withResponseShape'], api['endpointCount'])} |
| Confirmed working live (`OK`) | {api['liveOk']} | {pct(api['liveOk'], api['endpointCount'])} |
| Returned an error live (account/state-gated) | {api['liveError']} | {pct(api['liveError'], api['endpointCount'])} |
| Static-only (no runtime confirmation) | {api['endpointCount'] - api['withLiveEvidence']} | {pct(api['endpointCount'] - api['withLiveEvidence'], api['endpointCount'])} |

Only **{pct(api['withResponseShape'], api['endpointCount'])}** of the original surface has a captured
response shape. Everything else is a known *name* without a known *contract* — buildable only after
further capture.

## 3. By category

| Category | Endpoints | Live OK | With response shape |
|---|---:|---:|---:|
{chr(10).join(rows)}

## 4. The rebuild

**{rb['routeCount']} routes implemented.** Exposure: {json.dumps(rb['exposure'])}

| Module | Routes |
|---|---:|
{chr(10).join(f'| {m} | {n} |' for m, n in rb_by_mod.most_common())}

- Validated with a schema: {sum(1 for r in rb['routes'] if r['validated'])} / {rb['routeCount']} ({pct(sum(1 for r in rb['routes'] if r['validated']), rb['routeCount'])})
- Rate-limited: {sum(1 for r in rb['routes'] if r['rateLimit'])} / {rb['routeCount']}
- **Unguarded: 0** (closed in P1)

## 5. Endpoint parity

Counting endpoints alone is misleading in both directions: the original list contains
duplicates (three ids for `getRoomInfo`) and deprecated entries (`room.getVipUserRank` returns
*unfound action in table* on the live host today), while the rebuild has routes with no original
counterpart (13 agency endpoints vs the original's 8).

**Raw ratio: {rb['routeCount']} / {api['endpointCount']} = {pct(rb['routeCount'], api['endpointCount'])}** — reported for completeness,
not as a parity claim. The defensible measure is §Parity Report, which counts per-system behaviour.

## 6. DTO models

{api['dtoModels']} decompiled Gson classes carrying {api['dtoFieldTotal']} JSON fields — the
request/response field inventory of the original client. Full list in `master-dataset.json`
(`originalDtoModels`).

## 7. Errors

Observed error messages from live captures: {json.dumps(api['observedErrorMessages'], ensure_ascii=False)}

Numeric code tokens seen in decrypted strings (frequency): {json.dumps(dict(list(api['errorCodeTokens'].items())[:12]))}

**UNKNOWN:** the original's full error-code table was never captured. Only the messages above are
evidenced. No code-to-meaning mapping is asserted.
""")

# ------------------------------------------------------------------ SOCKET
s = D['socket']
w('MASTER_SOCKET_MAP.md', f"""# MASTER SOCKET / REALTIME MAP

{HDR}
## 1. Rebuild server events

**{s['serverEventCount']} distinct events**, all on a single `'event'` channel with the envelope
`{{ev, room, seq, ts, data}}` and a per-room sequence number.

| Event | Emit sites |
|---|---:|
{chr(10).join(f"| `{k}` | {v} |" for k, v in s['serverEmits'].items())}

## 2. Client consumption

**Client handles {s['clientEventCount']}:** {', '.join('`' + e + '`' for e in s['clientConsumes'])}

### Unconsumed by the client ({len(s['unconsumed'])})

{chr(10).join('- `' + e + '`' for e in s['unconsumed'])}

These are **not dead on the server** — they are emitted and delivered, but no client handler acts
on them. That is a client gap, not a protocol gap.

### Handled by the client with no server emitter ({len(s['clientOnlyNoServer'])})

{chr(10).join('- `' + e + '`' for e in s['clientOnlyNoServer']) or '- (none)'}

{'These handlers can never fire — the server never emits these names. Either the emitter is missing or the handler is dead code.' if s['clientOnlyNoServer'] else ''}

## 3. Original realtime protocol

The original did **not** use Socket.IO. It used a binary IM protocol; **{s['originalImOpcodes']} opcodes**
were recovered (`analysis/im_opcodes.json`).

**This is the single largest realtime unknown.** Our event vocabulary is a rebuild-owned design, not
a recovered one. Mapping {s['originalImOpcodes']} original opcodes onto {s['serverEventCount']} rebuilt
events has **not** been done and cannot be done from static evidence alone — it needs a capture of
the live IM socket, which no session has performed.

**Realtime parity is therefore UNKNOWN, not a percentage.** Any number here would be invented.

## 4. Missing mechanics

| Mechanic | Status |
|---|---|
| Heartbeat / ping-pong | Socket.IO built-in; the original's interval is UNKNOWN |
| ACK models | none in the rebuild; original UNKNOWN |
| Reconnection grace period | **not implemented** — a dropped client is treated as gone immediately |
| Retry / backoff | client `enableReconnection()`; server has no replay buffer |
| Sequence gap recovery | `seq` is emitted but the client never detects a gap |
""")

# ------------------------------------------------------------------ DATABASE
db = D['database']
big = sorted(db['models'], key=lambda m: -(db['rowCounts'].get(m['model']) or 0))[:15]
w('MASTER_DATABASE_MAP.md', f"""# MASTER DATABASE MAP

{HDR}
## Summary

| Metric | Value |
|---|---:|
| Prisma models | {db['modelCount']} |
| Migrations | {db['migrations']} |
| `@@index` declarations | {db['totalIndexes']} |
| Models with soft delete | **{db['modelsWithSoftDelete']} / {db['modelCount']}** |

**Finding — there is no soft-delete strategy.** `deletedAt` appears on
{db['modelsWithSoftDelete']} model. A production social platform deleting user content, rooms or
financial records by hard delete has no recovery path and no audit trail for the deletion itself.

## Models by live row count

| Model | Rows | Fields | Indexes | Relations |
|---|---:|---:|---:|---:|
{chr(10).join(f"| {m['model']} | {db['rowCounts'].get(m['model'], 'n/a')} | {m['fieldCount']} | {m['indexes']} | {m['relations']} |" for m in big)}

Row counts come from the **development** database and are inflated by test fixtures; they indicate
which tables are exercised, not production volume.

## Full model list

{', '.join(sorted(m['model'] for m in db['models']))}
""")

# ------------------------------------------------------------------ CATALOG
c = D['catalog']
w('MASTER_CATALOG_MAP.md', f"""# MASTER CATALOG MAP

{HDR}
## What the original actually gave us

| Catalogue | Recovered from capture | Detail |
|---|---:|---|
| Gifts | **{c['recoveredGifts']['count']}** | {c['recoveredGifts']['withImage']} with image, {c['recoveredGifts']['withPrice']} with price — real `gid`s |
| Decorations | **{c['recoveredDecorations']['count']}** | CP-reward items with real ids and names |
| Noble tiers | **{c['recoveredNobleTiers']['count']}** | real levels + real prices |
| Wealth ladder | **{c['recoveredWealthLadder']['count']}** | exact `minExp` per level |
| Medals | **{c['recoveredMedals']['count']}** | {c['recoveredMedals']['note']} |
| VIP tiers | 0 | never captured as a catalogue |
| Room themes | 0 | **no catalogue endpoint exists in the original surface** |
| Mall / shop | 0 | `mall.getMallProductV` never captured |
| Lucky bag / magic box | 0 | prize art captured; **odds never** |

Original decoration `type` codes observed: {json.dumps(c['recoveredDecorations']['originalTypes'])}
— these do **not** map to the rebuild's `DecorationItem.kind` (0/1/2). The codebook is UNKNOWN and
the importer deliberately leaves `kind` unset rather than guess.

## What the rebuild holds

| Table | Rows |
|---|---:|
{chr(10).join(f'| {k} | {v} |' for k, v in c['rebuildRows'].items())}

**These rows are development fixtures plus invented seed data**, not the original catalogue. The
seed writes six invented gifts, three invented VIP tiers and three invented room themes; the only
genuinely original rows are the 10 gifts imported from `couple.cpGiftList`.

## Catalogue parity

| Catalogue | Original entities recovered | In rebuild as original data | Parity |
|---|---:|---:|---:|
| Gifts | {c['recoveredGifts']['count']} | 10 | {pct(10, c['recoveredGifts']['count'])} of what we recovered — and the original's full list is UNKNOWN |
| Noble | {c['recoveredNobleTiers']['count']} | 0 | 0% — captured but not modelled |
| Wealth ladder | {c['recoveredWealthLadder']['count']} | 0 | 0% — captured but not imported |
| Decorations | {c['recoveredDecorations']['count']} | 0 | 0% — blocked on the `kind` codebook |
| Medals | 0 | 0 | UNKNOWN — nothing to import |

**The binding constraint is not engineering.** Three of these five are already captured and simply
not yet imported; one is blocked on a codebook; one has no evidence at all.
""")

# ------------------------------------------------------------------ ASSETS
a = D['assets']
w('MASTER_ASSET_MAP.md', f"""# MASTER ASSET MAP

{HDR}
## Inventory

| Store | Files | Bytes |
|---|---:|---:|
| Bundled in the Flutter app | {a['bundledFiles']} | {a['bundledBytes'] / 1e6:.1f} MB |
| Recovered H5 archive (verified) | {a['archiveFiles']} | {a['archiveBytes'] / 1e6:.1f} MB |
| Stored on our R2 origin | {a['onR2']} ({a['onR2Mirrored']} mirrored) | {a['onR2Bytes'] / 1e6:.1f} MB |

Bundled by type: {json.dumps(a['bundledByExt'])}

## Registry coverage

| Metric | Value |
|---|---:|
| Registry entries (every bundled file named) | {a['registryEntries']} / {a['bundledFiles']} ({pct(a['registryEntries'], a['bundledFiles'])}) |
| Registry ids a screen actually names | **{a['registryReferencedByScreens']}** |

**Finding.** Every bundled asset is catalogued, but screens name only
**{a['registryReferencedByScreens']}** of {a['registryEntries']} ids directly. Most art reaches the UI
through server-URL fields with a bundled fallback rather than by id, so a low number here is not the
same as unused art — but it does mean the registry is far from being the primary access path it was
built to be.

## Archive audit

{json.dumps(a['archiveAudit'], indent=2)}

## Legacy-host dependency

**Zero.** The database contains no URL on any legacy host (verified across 8 asset columns and 6
host patterns). The 10 live rows were mirrored to R2 and rewritten.
""")

# ------------------------------------------------------------------ FLUTTER
f_ = D['flutter']
w('MASTER_FLUTTER_MAP.md', f"""# MASTER FLUTTER MAP

{HDR}
| Metric | Value |
|---|---:|
| State management | {f_['stateManagement']} |
| Dart files | {f_['dartFiles']} |
| Screens | {f_['screenFiles']} |
| Routes | {f_['routeCount']} |
| Riverpod providers | {f_['providerCount']} |
| Repositories | {len(f_['repositories'])} |
| Model files | {f_['modelFiles']} |

## Routes

{chr(10).join('- `' + r + '`' for r in f_['routes'])}

## Repositories

{', '.join(sorted(f_['repositories']))}

## Providers

{', '.join(sorted(f_['providers']))}

## Coverage vs the original

The original shipped **81 Android activities** and **{D['h5']['pagesLive']} live H5 pages**. The
rebuild has **{f_['screenFiles']} screens**. Activity count is not directly comparable (one Flutter
screen can replace several activities, and some activities are dialogs), so no percentage is
asserted here — see the parity report for per-system figures.

## Known client gaps

- **{len(D['socket']['unconsumed'])} server events have no handler** (see the socket map).
- **Storage keys: {len(D['constants']['flutterStorageKeys'])}** — `{', '.join(D['constants']['flutterStorageKeys'])}`. The original's
  SharedPreferences surface is far larger ({D['constants']['apkWaitioTokenCount']} `waitio_*` tokens in the
  decrypted strings, though not all are storage keys).
- **No offline/connectivity handling** was found.
- **The Flutter test toolchain does not run in this environment** — `flutter_test` fails to compile
  across all three installed SDKs. No client test has ever executed here, so every client claim in
  this project rests on static analysis alone.
""")

# ------------------------------------------------------------------ H5
h = D['h5']
w('MASTER_H5_MAP.md', f"""# MASTER H5 MAP

{HDR}
| Metric | Value |
|---|---:|
| Candidates probed | {h['candidatesProbed']} |
| **Live pages (HTTP 200)** | **{h['pagesLive']}** |
| 404 | {h['pages404']} |
| Requiring a session (401/403) | {h['requireAuth']} |
| Bundles held locally | {h['bundlesHeld']} |
| Pages with archived assets | {len(h['archivedPages'])} |

## Live pages

{', '.join('`' + p + '`' for p in h['livePageNames'])}

## Discovery method accuracy

{json.dumps(h['discoveryConfidence'])}

Of 78 names guessed from convention, **zero existed**. Of 31 names derived from recovered code,
**all 31 existed**. Page names in this system are not guessable (`wealth_grade`, `my_level`,
`roomGroupRule`) — evidence-derived discovery worked, convention-based guessing did not.

## Authentication

**No page requires a session for its HTML shell.** Authentication happens inside the page's JS via
the token in the query string. Asset collection therefore needs no credentials.

## Archived pages

{', '.join(h['archivedPages'])}
""")

# ------------------------------------------------------------------ ECONOMY
w('MASTER_ECONOMY_MAP.md', f"""# MASTER ECONOMY MAP

{HDR}
## Currencies in the rebuild

From `prisma/schema.prisma` — `Wallet` carries `coins`, `coinsTotal`, `vipCoins`, `beans`,
`balance`, plus a `version` column for optimistic locking. `WalletLedger` records
`currency` (0 coins · 1 beans · 2 vipCoins · 3 balance), `delta`, `balanceAfter`, `reason`,
`refType`/`refId`, and a unique `idempotencyKey`.

## Verified properties (tested under concurrency)

| Property | Status |
|---|---|
| Single sanctioned mutator (`applyDelta`) | enforced by an architecture test |
| Serializable transaction per mutation | yes |
| Optimistic lock column | yes (`Wallet.version`) |
| Append-only ledger with `balanceAfter` | yes |
| Idempotency — Redis guard | yes |
| Idempotency — database backstop | **added in P1**; previously the unique column was never populated |
| No double-spend under 20 concurrent debits | proven by test |
| No lost update under 25 concurrent credits | proven by test |
| Ledger reconciles to balance | proven by test |

## What the original's economy actually is — UNKNOWN

None of the following was ever captured, and none is invented in the rebuild:

| Constant | Status |
|---|---|
| Gift → charm ratio | UNKNOWN |
| Gift → beans (receiver income) split | UNKNOWN |
| Room experience accrual | UNKNOWN — the rebuild deliberately has **no** `roomExp` mutation |
| Agency commission rate | UNKNOWN — `rateBps` column exists, no recovered value |
| Withdrawal minimum / maximum | UNKNOWN |
| Recharge product prices | partially — `subProductList.php` known by name, contents never captured |
| Lucky-draw odds | UNKNOWN — **and unrecoverable without the operator** |

## Recovered economic facts

| Fact | Value | Source |
|---|---|---|
| Noble tier prices | 15 tiers, 500 000 → 250 000 000 | `Action/Noble.getUserNoble` capture |
| Wealth ladder thresholds | 100 levels, exact `minExp` each | `user.getWealthCfg` capture |
| CP gift prices | 20 gifts with real prices | `couple.cpGiftList` capture |

## Missing subsystems

Withdrawal flow (pending → review → approved), agency settlement job, family commission, PK rewards,
inventory/consumption reporting — **none implemented**.
""")

# ------------------------------------------------------------------ PROTOCOL MAP
w('MASTER_PROTOCOL_MAP.md', f"""# MASTER PROTOCOL MAP

{HDR}
The chain the brief asked for — Screen → API → Socket → DB → Prisma → Flutter model → widget →
assets — can only be drawn where every link is evidenced. Below, each row states what is known and
what is UNKNOWN; a blank is never filled by inference.

| Screen (rebuild) | API | Socket | Prisma model | Assets | Original counterpart |
|---|---|---|---|---|---|
| `/login` | `POST /auth/login`, `/auth/refresh` | — | User, Profile | brand, `svga/login` | `login.checkMobile`, `GetUserSig` |
| `/home` | `GET /rooms`, `/config/bootstrap` | — | Room | `pag/home` (5 tabs), `svga/home` | `room.discoverRoom` |
| `/room/:id` | `GET /rooms/:id`, `/seats`, `/online`, `POST /rooms/:id/join` | `seat.update`, `mic.update`, `room.joined`, `chat.message`, `gift.received` | Room, Seat, RoomMember | `svga/kroom` (29), `pag/kroom`, `svga/yinbo` | `RoomApi.*`, `LiveRoom.*` (101 endpoints) |
| `/profile`, `/profile/:uid` | `GET /users/:id`, `/levels`, `/gift-wall`, `/couple` | — | Profile, UserMedal, Couple | `pag/userspace` (15), `svga/userspace` | `user.getUserinfo` (DTO `t43`) |
| `/wallet` | `GET /wallet`, `/store/products` | — | Wallet, WalletLedger, Order | `h5/coinsMerchant` (9) | `wallet.getWalletInfo`, `subProductList.php` |
| `/vip` | `GET /vip/plans`, `/vip/me` | `vip.purchased` | VipLevel, VipHistory | `pag/userspace/waitio_vip*` | `Noble.*`, `SVip.*` — **separate systems, absent** |
| `/agency`, `/agency/:id` | 13 `/agencies/*` | — | Agency, AgencyMember, CommissionRecord | `h5/anchor` (69), `svga/hosttag` | `Anchor.*`, `Guild.*`, `BDCenter.*` |
| `/couple` | `/couple/*` (6) | `couple.invite/accepted/broken` | Couple | `h5/cpReward`, `svga/cp`, `pag/cp` | `couple.cpHouse`, `cpGiftList` |
| `/rankings` | `GET /rankings` | `rank.update` | RankingScore | `pag/rank` | `room.getUserCharmRankV` |
| `/medals` | `GET /medals`, `/users/:id/medals` | — | Medal, UserMedal | `svga/medal` | `medal.getMedalList` — **catalogue never captured** |
| `/settings` | `GET/PATCH /users/me/settings` | — | Profile | — | `HiddenSettings.*` |
| `/moments` | `/moments/*` | `moment.like`, `moment.comment` | Moment, MomentComment | `svga/dynamic` | `moment.history` |
| `/dm/:uid` | `/dm/*` | `dm.message` | DmConversation, DmMessage | — | `UsersRoamMsg.*` |
| — **no screen** | — | `pk.updated`, `bomb.*`, `pool.*` | RoomPk | `svga/kroom/waitio_pk_*` (22), `pag/bomb` (16) | `LivePk.*`, `RoomBomb.*` |
| — **no screen** | `GET /decorations` | — | DecorationItem, UserDecoration | zip bundles (unplayable) | `mall.getMallProductV` |
| — **no screen** | `/tasks/*` | — | Task, UserTask | `h5/task` | `Quests.*`, `MagicBox.*` |

## Protocol-level UNKNOWNS

1. **The original realtime protocol is not Socket.IO.** {D['socket']['originalImOpcodes']} binary IM
   opcodes were recovered; none has been mapped to a rebuilt event. Our event vocabulary is
   rebuild-owned.
2. **`avatarFrameJson` / `carFrameJson`** — fields observed on four DTOs, contents never captured.
3. **`srcType` codebook** — three observations from one user.
4. **Error-code table** — only the error *messages* below were ever observed.
""")

# ------------------------------------------------------------------ PARITY
def sysrow(name, have, total, note, status):
    return f"| {name} | {have} | {total} | {pct(have, total) if total else 'UNKNOWN'} | {status} | {note} |"


parity = [
    sysrow('API surface', rb['routeCount'], api['endpointCount'], 'union of both evidence sources', 'PARTIAL'),
    sysrow('API with known contract', rb['routeCount'], api['withResponseShape'], f"only {api['withResponseShape']} originals have a captured shape", 'EXCEEDS'),
    sysrow('Realtime events', D['socket']['clientEventCount'], D['socket']['serverEventCount'], 'client vs our own server', 'PARTIAL'),
    sysrow('Realtime vs ORIGINAL protocol', 0, D['socket']['originalImOpcodes'], 'binary IM opcodes, none mapped', 'UNKNOWN'),
    sysrow('H5 pages archived', len(D['h5']['archivedPages']), D['h5']['pagesLive'], 'assets captured per live page', 'GOOD'),
    sysrow('Gift catalogue', 10, c['recoveredGifts']['count'], 'imported vs recovered', 'PARTIAL'),
    sysrow('Noble tiers', 0, c['recoveredNobleTiers']['count'], 'captured, not modelled', 'MISSING'),
    sysrow('Wealth ladder', 0, c['recoveredWealthLadder']['count'], 'captured, not imported', 'MISSING'),
    sysrow('Decoration catalogue', 0, c['recoveredDecorations']['count'], 'blocked on the kind codebook', 'BLOCKED'),
    sysrow('Medal catalogue', 0, 0, 'no evidence exists', 'UNKNOWN'),
    sysrow('Assets on our origin', a['onR2Mirrored'], a['archiveFiles'], 'archive uploaded to R2', 'GOOD'),
    sysrow('Legacy-host dependency', 0, 0, 'zero legacy URLs in the database', 'DONE'),
]

w('MASTER_PARITY_REPORT.md', f"""# MASTER PARITY REPORT

{HDR}
## Method

Every row counts discovered elements. Where the denominator itself is unknown — because the
original's full list was never captured — the cell says **UNKNOWN** rather than a number. A
percentage against an unknown denominator would be fiction.

## Per-system parity

| System | Have | Total known | Parity | Status | Basis |
|---|---:|---:|---:|---|---|
{chr(10).join(parity)}

## The denominator problem

The single most important correction in this extraction: the original surface is
**{api['endpointCount']} endpoints**, not 280. Static APK analysis found {api['fromApkStatic']};
live H5 capture found {api['fromH5LiveCapture']}; they overlap on only {api['overlap']}. Every earlier
parity estimate in this project used the smaller number and was therefore **optimistic by about a
third**.

And of those {api['endpointCount']}, only **{api['withResponseShape']}** have a captured response
shape. So the true state is:

- **{api['withResponseShape']} endpoints** we could faithfully rebuild today (contract known).
- **{api['withLiveEvidence'] - api['withResponseShape']} endpoints** whose name and parameters are known but whose response is not.
- **{api['endpointCount'] - api['withLiveEvidence']} endpoints** known only as a name from static analysis.

The rebuild's {rb['routeCount']} routes already exceed the {api['withResponseShape']} fully-specified
originals. **Further endpoint parity is capture-bound, not engineering-bound.**

## Honest overall figure

A single project-wide percentage cannot be computed, because for several systems the denominator is
unknown. What can be said, counted:

| Measure | Value |
|---|---:|
| Original endpoints with a known contract, implemented | high — the rebuild has more routes than there are fully-specified originals |
| Original endpoints total, implemented | {pct(rb['routeCount'], api['endpointCount'])} (raw ratio; see caveats) |
| Recovered catalogue entities imported | {pct(10, c['recoveredGifts']['count'] + c['recoveredNobleTiers']['count'] + c['recoveredDecorations']['count'] + c['recoveredWealthLadder']['count'])} |
| Recovered assets stored on our own origin | {pct(a['onR2Mirrored'], a['archiveFiles'])} |
| Realtime protocol parity with the original | **UNKNOWN** — {D['socket']['originalImOpcodes']} opcodes unmapped |
| Legacy-host runtime dependency | **0** |

## Classification

**EXACT** — wallet ledger semantics, seat state machine, auth rotation, asset integrity pipeline.

**DIFFERENT** — realtime transport (Socket.IO vs the original's binary IM); catalogue rows (invented
seed vs original entities); VIP modelled as one system where the original had three.

**MISSING** — Noble, SVIP, Family, coin merchant, events/activities, mounts, friend intimacy,
withdrawal flow, agency settlement, admin UI, gift board UI, emoji picker.

**UNUSED / DEAD** — {len(D['socket']['unconsumed'])} server events with no client handler;
{a['registryEntries'] - a['registryReferencedByScreens']} registry ids no screen names directly (most
reach the UI via server-URL fallback, so this is not all dead).

**UNKNOWN** — see below; {len(D['unknown'])} items with no evidence.

## What cannot be recovered

{chr(10).join(f"{i + 1}. **{u['item']}** — {u['why']}. Blocks: {u['blocks']}." for i, u in enumerate(D['unknown']))}
""")

# ------------------------------------------------------------------ STATUS
w('PROJECT_COMPLETION_STATUS.md', f"""# PROJECT COMPLETION STATUS

{HDR}
## Systems

| System | State | Can finish now? | Needs capture? | Recoverable? |
|---|---|---|---|---|
| Auth / identity | Functional | yes | no | yes |
| Users / profile | Functional | yes | partly (extended fields) | yes |
| Voice rooms | Partial — largest gap | yes (UI work) | no | yes |
| Gifts | Partial | yes (UI) | **yes** (full catalogue) | yes |
| Wallet / economy core | Strong, concurrency-proven | yes | no | yes |
| Economy constants | Absent | **no** | **yes** | UNKNOWN |
| VIP | Partial (invented tiers) | no | **yes** | yes |
| Noble | Missing | **yes — 15 tiers already captured** | no | yes |
| SVIP | Missing | no | **yes** (needs an SVIP account) | UNKNOWN |
| Agency | Functional | yes | partly (hierarchy) | yes |
| Family | Missing | no | **yes** | UNKNOWN |
| Events / tasks | ~15% | partly | **yes** | odds UNRECOVERABLE |
| Realtime | Functional (own design) | yes | **yes** (IM socket) | protocol UNKNOWN |
| Assets | Complete + on R2 | done | no | yes |
| Admin | Routes only, no UI | yes | no | yes |
| Database | Functional | yes | no | yes |

## Immediately actionable — no new capture, no unknowns

1. Import the **15 Noble tiers** and **100 wealth-ladder levels** already sitting in captures.
2. Consume the **{len(D['socket']['unconsumed'])} unhandled server events** in the client.
3. Build the gift board, emoji picker (config already parsed) and room admin panel.
4. Add a reconnection grace period.
5. Soft-delete strategy and the FK-index review.
6. Withdrawal state machine; agency settlement job.

## Blocked on capture

`gift.getGiftList` · `mall.getMallProductV` · `medal.getMedalList` · `Action/SVip.*` (needs an SVIP
account) · guild endpoints (needs a guild member) · the live IM socket (realtime protocol).

## Blocked permanently

Gacha odds · economy constants · original ids and history.

## Operational

**`R2_PUBLIC_BASE_URL` is an `r2.dev` subdomain, which Cloudflare rate-limits and does not support
for production.** A custom domain is required before launch. Keys are content-addressed and
host-independent, so the switch is a manifest rebuild plus one rewrite pass.
""")

print('\nreports written to rebuild/reports/')
