package com.faceunity.core.enumeration;

import com.faceunity.wrapper.faceunity;

/* compiled from: zaffa */
/* loaded from: classes.dex */
public enum FUAITypeEnum {
    FUAITYPE_BACKGROUNDSEGMENTATION(2),
    FUAITYPE_HAIRSEGMENTATION(4),
    FUAITYPE_HANDGESTURE(8),
    FUAITYPE_TONGUETRACKING(32),
    FUAITYPE_FACELANDMARKS75(8192),
    FUAITYPE_FACELANDMARKS209(16384),
    FUAITYPE_FACELANDMARKS239(32768),
    FUAITYPE_HUMANPOSE2D(64),
    FUAITYPE_BACKGROUNDSEGMENTATION_GREEN(128),
    FUAITYPE_FACEPROCESSOR(256),
    FUAITYPE_FACEPROCESSOR_FACECAPTURE(faceunity.FUAITYPE_FACEPROCESSOR_FACECAPTURE),
    FUAITYPE_FACEPROCESSOR_FACECAPTURE_TONGUETRACKING(faceunity.FUAITYPE_FACEPROCESSOR_FACECAPTURE_TONGUETRACKING),
    FUAITYPE_FACEPROCESSOR_HAIRSEGMENTATION(faceunity.FUAITYPE_FACEPROCESSOR_HAIRSEGMENTATION),
    FUAITYPE_FACEPROCESSOR_HEADSEGMENTATION(8388608),
    FUAITYPE_FACEPROCESSOR_EXPRESSION_RECOGNIZER(faceunity.FUAITYPE_FACEPROCESSOR_EXPRESSION_RECOGNIZER),
    FUAITYPE_FACEPROCESSOR_EMOTION_RECOGNIZER(faceunity.FUAITYPE_FACEPROCESSOR_EMOTION_RECOGNIZER),
    FUAITYPE_HUMAN_PROCESSOR(512),
    FUAITYPE_HUMAN_PROCESSOR_DETECT(faceunity.FUAITYPE_HUMAN_PROCESSOR_DETECT),
    FUAITYPE_HUMAN_PROCESSOR_2D_SELFIE(faceunity.FUAITYPE_HUMAN_PROCESSOR_2D_SELFIE);

    private final int type;

    FUAITypeEnum(int i) {
        this.type = i;
    }

    public final int getType() {
        return this.type;
    }
}
