package p000;

import android.R;

/* compiled from: zaffa */
/* loaded from: classes3.dex */
public final class h54 {
    public static final int ColorStateListItem_alpha = 3;
    public static final int ColorStateListItem_android_alpha = 1;
    public static final int ColorStateListItem_android_color = 0;
    public static final int ColorStateListItem_android_lStar = 2;
    public static final int ColorStateListItem_lStar = 4;
    public static final int FlexboxLayout_Layout_layout_alignSelf = 0;
    public static final int FlexboxLayout_Layout_layout_flexBasisPercent = 1;
    public static final int FlexboxLayout_Layout_layout_flexGrow = 2;
    public static final int FlexboxLayout_Layout_layout_flexShrink = 3;
    public static final int FlexboxLayout_Layout_layout_maxHeight = 4;
    public static final int FlexboxLayout_Layout_layout_maxWidth = 5;
    public static final int FlexboxLayout_Layout_layout_minHeight = 6;
    public static final int FlexboxLayout_Layout_layout_minWidth = 7;
    public static final int FlexboxLayout_Layout_layout_order = 8;
    public static final int FlexboxLayout_Layout_layout_wrapBefore = 9;
    public static final int FlexboxLayout_alignContent = 0;
    public static final int FlexboxLayout_alignItems = 1;
    public static final int FlexboxLayout_dividerDrawable = 2;
    public static final int FlexboxLayout_dividerDrawableHorizontal = 3;
    public static final int FlexboxLayout_dividerDrawableVertical = 4;
    public static final int FlexboxLayout_flexDirection = 5;
    public static final int FlexboxLayout_flexWrap = 6;
    public static final int FlexboxLayout_justifyContent = 7;
    public static final int FlexboxLayout_maxLine = 8;
    public static final int FlexboxLayout_showDivider = 9;
    public static final int FlexboxLayout_showDividerHorizontal = 10;
    public static final int FlexboxLayout_showDividerVertical = 11;
    public static final int FontFamilyFont_android_font = 0;
    public static final int FontFamilyFont_android_fontStyle = 2;
    public static final int FontFamilyFont_android_fontVariationSettings = 4;
    public static final int FontFamilyFont_android_fontWeight = 1;
    public static final int FontFamilyFont_android_ttcIndex = 3;
    public static final int FontFamilyFont_font = 5;
    public static final int FontFamilyFont_fontStyle = 6;
    public static final int FontFamilyFont_fontVariationSettings = 7;
    public static final int FontFamilyFont_fontWeight = 8;
    public static final int FontFamilyFont_ttcIndex = 9;
    public static final int FontFamily_fontProviderAuthority = 0;
    public static final int FontFamily_fontProviderCerts = 1;
    public static final int FontFamily_fontProviderFallbackQuery = 2;
    public static final int FontFamily_fontProviderFetchStrategy = 3;
    public static final int FontFamily_fontProviderFetchTimeout = 4;
    public static final int FontFamily_fontProviderPackage = 5;
    public static final int FontFamily_fontProviderQuery = 6;
    public static final int FontFamily_fontProviderSystemFontFamily = 7;
    public static final int GradientColorItem_android_color = 0;
    public static final int GradientColorItem_android_offset = 1;
    public static final int GradientColor_android_centerColor = 7;
    public static final int GradientColor_android_centerX = 3;
    public static final int GradientColor_android_centerY = 4;
    public static final int GradientColor_android_endColor = 1;
    public static final int GradientColor_android_endX = 10;
    public static final int GradientColor_android_endY = 11;
    public static final int GradientColor_android_gradientRadius = 5;
    public static final int GradientColor_android_startColor = 0;
    public static final int GradientColor_android_startX = 8;
    public static final int GradientColor_android_startY = 9;
    public static final int GradientColor_android_tileMode = 6;
    public static final int GradientColor_android_type = 2;
    public static final int RecyclerView_android_clipToPadding = 1;
    public static final int RecyclerView_android_descendantFocusability = 2;
    public static final int RecyclerView_android_orientation = 0;
    public static final int RecyclerView_fastScrollEnabled = 3;
    public static final int RecyclerView_fastScrollHorizontalThumbDrawable = 4;
    public static final int RecyclerView_fastScrollHorizontalTrackDrawable = 5;
    public static final int RecyclerView_fastScrollVerticalThumbDrawable = 6;
    public static final int RecyclerView_fastScrollVerticalTrackDrawable = 7;
    public static final int RecyclerView_layoutManager = 8;
    public static final int RecyclerView_reverseLayout = 9;
    public static final int RecyclerView_spanCount = 10;
    public static final int RecyclerView_stackFromEnd = 11;
    public static final int[] ColorStateListItem = {R.attr.color, R.attr.alpha, R.attr.lStar, com.waig.nalo.R.attr.f49021ao, com.waig.nalo.R.attr.f49853x8};
    public static final int[] FlexboxLayout = {com.waig.nalo.R.attr.al, com.waig.nalo.R.attr.am, com.waig.nalo.R.attr.n4, com.waig.nalo.R.attr.n5, com.waig.nalo.R.attr.n6, com.waig.nalo.R.attr.s0, com.waig.nalo.R.attr.s1, com.waig.nalo.R.attr.x4, com.waig.nalo.R.attr.a21, com.waig.nalo.R.attr.a9h, com.waig.nalo.R.attr.a9i, com.waig.nalo.R.attr.a9j};
    public static final int[] FlexboxLayout_Layout = {com.waig.nalo.R.attr.xi, com.waig.nalo.R.attr.z0, com.waig.nalo.R.attr.z1, com.waig.nalo.R.attr.z2, com.waig.nalo.R.attr.zd, com.waig.nalo.R.attr.ze, com.waig.nalo.R.attr.zf, com.waig.nalo.R.attr.zg, com.waig.nalo.R.attr.zi, com.waig.nalo.R.attr.zm};
    public static final int[] FontFamily = {com.waig.nalo.R.attr.f49698t1, com.waig.nalo.R.attr.f49699t2, com.waig.nalo.R.attr.f49700t3, com.waig.nalo.R.attr.f49701t4, com.waig.nalo.R.attr.f49702t5, com.waig.nalo.R.attr.f49703t6, com.waig.nalo.R.attr.f49704t7, com.waig.nalo.R.attr.f49705t8};
    public static final int[] FontFamilyFont = {R.attr.font, R.attr.fontWeight, R.attr.fontStyle, R.attr.ttcIndex, R.attr.fontVariationSettings, com.waig.nalo.R.attr.f49696sz, com.waig.nalo.R.attr.f49706t9, com.waig.nalo.R.attr.f49707t_, com.waig.nalo.R.attr.f49708ta, com.waig.nalo.R.attr.ahp};
    public static final int[] GradientColor = {R.attr.startColor, R.attr.endColor, R.attr.type, R.attr.centerX, R.attr.centerY, R.attr.gradientRadius, R.attr.tileMode, R.attr.centerColor, R.attr.startX, R.attr.startY, R.attr.endX, R.attr.endY};
    public static final int[] GradientColorItem = {R.attr.color, R.attr.offset};
    public static final int[] RecyclerView = {R.attr.orientation, R.attr.clipToPadding, R.attr.descendantFocusability, com.waig.nalo.R.attr.f49648ro, com.waig.nalo.R.attr.f49649rp, com.waig.nalo.R.attr.f49650rq, com.waig.nalo.R.attr.f49651rr, com.waig.nalo.R.attr.f49652rs, com.waig.nalo.R.attr.f49863xh, com.waig.nalo.R.attr.a7c, com.waig.nalo.R.attr.a_d, com.waig.nalo.R.attr.aa0};
}
